// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbTR8Lqik62C8ALCbQJb0aPWaQCzvqdY',
    appId: '1:915922002708:web:e79870913e00ca75c29801',
    messagingSenderId: '915922002708',
    projectId: 'todo-list-441be',
    authDomain: 'todo-list-441be.firebaseapp.com',
    storageBucket: 'todo-list-441be.appspot.com',
    measurementId: 'G-NT1DMYH8SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbB8yOvG-VUllXgGERPUQwCes6ci0gAus',
    appId: '1:915922002708:android:f583854140a8a45fc29801',
    messagingSenderId: '915922002708',
    projectId: 'todo-list-441be',
    storageBucket: 'todo-list-441be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQSaA1g5xerqElpfg39bY251MVytEXbQ',
    appId: '1:915922002708:ios:1058155cd2d6deecc29801',
    messagingSenderId: '915922002708',
    projectId: 'todo-list-441be',
    storageBucket: 'todo-list-441be.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQSaA1g5xerqElpfg39bY251MVytEXbQ',
    appId: '1:915922002708:ios:1931e8cc6e59e785c29801',
    messagingSenderId: '915922002708',
    projectId: 'todo-list-441be',
    storageBucket: 'todo-list-441be.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
